### ISSUE TITLE
Feature Request: Hive Template Integration

### ISSUE THREAD

**Issue by megan201296** [TTP0/drone#3]
It would be awesome if during the "run" function for drone, a template to use for the Hive case could be specified so that we can use drone to create cases while still leveraging the template feature of thehive.

**Comment by dfirence** [comment]
Hi Megan

Thank you for requesting ghis enhancements and would like offer some initial thoughts on your request.

When you say “templates”, are you envisioning:

1.  DRONE displays a list of existing templates created in the UI of TheHive, and present those templates to you to expedite case creation?

Or

2.  DRONE allowing you to create your own templates, store them locally and in the UI of TheHive, and finally allowing you to use those templates to create cases?


Currently, the way you are using DRONE, it is creating “light-weight” cases from templates based on our TTP0 approach with the CAT0-9 design. 

What we did not release are/were other items for the cases, like tasks based on the category chosen, which would make it a full case template. 

We did this because we could not predict the tasks we commonly used as a team in previous experiences could be useful to others unless we got feedback confirming. Also we needed to understand the REST APIs provided the DEV TEAM from TheHive would offer stability as they moved to the newer versions - seems that is good to go. 

Sorry for the length, just want to ensure we understand the request to service you and other DRONE users to the best of our ability.

**Comment by megan201296** [comment]
@dfirence I was thinking (1). An additional option as you are stepping through the "run" function that asks what template you'd like to apply so that tasks are created appropriately.

**Comment by dfirence** [comment]
Cool, where would those templates reside so DRONE can present them during “run”?

**Comment by megan201296** [comment]
@dfirence we are about hitting the limit of my technical understanding. I was hoping (but have not researched) that the Hive API allows you to specify templates and thus the API call to create the case could contain a variable based on . a selection from the menu. I could be making up things that don't work but without a deep technical understanding that is what I envisioned.

**Comment by megan201296** [comment]
@dfirence it looks like TheHive4Py allows for specifying templates but the Rest API does not, so guess it depends on which API method you are using.

**Comment by dfirence** [comment]
Hey Maegen@

I like where you going with this. 

Would be open to web conferencing, it is easier for me versus typing here.

I would like to explore what you pursuing. 

If ok, send me an email to carlos@ttp0.io

**Comment by dfirence** [comment]
Maegen, hope you are well. Lets reopen this in the future as we get more usecase inputs. 

Please feel free yo reach out directly
